# ⚠️ DEPRECATION WARNING ⚠️
# This template is DEPRECATED and will be removed in a future version.
# Please migrate to the new unified trivy-scanning.template.yaml
# 
# Migration guide:
# Replace this:
#   extends: .config_scanning
# With this:
#   extends: .trivy_scanning
#   variables:
#     PLUGIN_SEVERITY_MISCONFIG: "MEDIUM,HIGH,CRITICAL,UNKNOWN"
#     PLUGIN_PKG_TYPES_MISCONFIG: "library, os"
#
# For more information, see: https://github.com/ambient-innovation/trivy-scanner-templates/releases/latest

.config_scanning:
  extends: .trivy_scanning
  variables:
    # Deprecated: Use the new trivy_scanning template directly
    PLUGIN_SEVERITY_MISCONFIG: "MEDIUM,HIGH,CRITICAL,UNKNOWN"
    PLUGIN_PKG_TYPES_MISCONFIG: "library, os"
    # Override scanner types for config-only scanning
    TRIVY_SCANNERS: "misconfig"
  before_script:
    # Show deprecation warning
    - echo "⚠️  WARNING: The .config_scanning template is DEPRECATED!"
    - echo "⚠️  Please migrate to .trivy_scanning template."
    - echo "⚠️  See migration guide: https://github.com/$ambient-innovation/trivy-scanner-templates/releases/latest"
    - echo "⚠️  This template will be removed in a future version."
    - echo ""
    # Call parent before_script
    - !reference [.trivy_scanning, before_script]

# Include the new unified template
include:
  - remote: 'https://github.com/ambient-innovation/gitlab-trivy-codequality-template/releases/download/v25.08.05.0trivy-scanning.template.yaml'
